### DISCUSSION TITLE
bug: Meta database configuration missing database name

### DISCUSSION THREAD

**Discussion by cellarliang** [nocodb/nocodb#11237] [General]
pls help me find something wrong with the  docker-compose yaml file? Coz when i check docker ps -a ,the nocodb status isn't show as "up",it show as "restarting",how can i make the nocodb status shows as "up"
when i check the docker logs ,it shows as below

```
root@server-VMware-Virtual-Platform:~/nocodb# docker ps -a
CONTAINER ID   IMAGE                  COMMAND                   CREATED         STATUS                          PORTS                                                    NAMES
a4d3d4c673f5   nocodb/nocodb:latest   "/usr/bin/dumb-init …"   3 minutes ago   Restarting (1) 22 seconds ago                                                            nocodb
7cfdd3c7df52   mysql:8.0              "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (healthy)          0.0.0.0:3306->3306/tcp, [::]:3306->3306/tcp, 33060/tcp   mysql-nocodb
f49aff3dd725   centos                 "/bin/sh -c 'while t…"   4 hours ago     Up 4 hours                                                                               friendly_pascal
f7bd43da5d0a   centos                 "bin/bash"                4 hours ago     Exited (0) 4 hours ago                                                                   magical_carver
83e2cc288b95   centos                 "bin/bash"                4 days ago      Exited (0) 4 days ago                                                                    lucid_taussig
```
the docker logs nocodb show the error as below,"Meta database configuration missing database name"

```
root@server-VMware-Virtual-Platform:~/nocodb# docker logs nocodb
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [NestFactory] Starting Nest application...
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 8  - 04/28/2025, 11:26:49 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 8  - 04/28/2025, 11:26:49 AM   ERROR [ExceptionHandler] Error: Meta database configuration missing database name
Error: Error: Meta database configuration missing database name
    at NcConfig.create (/usr/src/app/docker/main.js:1775:37643)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:1752:280626)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:377:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:145:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:98:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
```
the docker-compose.yml show as below:
```
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-nocodb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nocodb1040402541cell
      MYSQL_DATABASE: nocodb
      MYSQL_USER: nocodbcellar
      MYSQL_PASSWORD: testnocodb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      NC_DB: "mysql2://nocodbcellar:testnocodb@mysql-nocodb:3306/nocodb"
    restart: always
    volumes:
      - ./nocodb_data:/usr/app/data

volumes:
  mysql_data:
  nocodb_data:
```
