### DISCUSSION TITLE
How to set NC_AUTH_JWT_SECRET from docker-compose.yml file

### DISCUSSION THREAD

**Discussion by ashgard071** [nocodb/nocodb#4338] [Q&A]
Hi 

I have a docker-compose.yml file to start all services for my app, including nocodb. A snippet from the docker-compose.yml looks as follows:

```
  noco_db:
    depends_on:
      root_db:
        condition: service_healthy
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - nc_data:/usr/app/data
    environment:
      NC_DB: "mysql2://host.docker.internal:3306?u=noco&p=password&d=root_db"
      NC_AUTH_JWT_SECRET: "569a1821-0a93-45e8-87ab-eb857f20a010"
```

I set the NC_AUTH_JWT_SECRET as environment variable as described here: https://docs.nocodb.com/getting-started/installation/

However, for some reason my app can't authenticate using the secret defined above. However, if I follow the instructions as shown here https://docs.nocodb.com/developer-resources/accessing-apis/#auth-token, then my app can authenticate. 

What am I doing wrong why the value of the env var NC_AUTH_JWT_SECRET is not properly set? 

Best
Ashgard
