### DISCUSSION TITLE
SSL metadata DB

### DISCUSSION THREAD

**Discussion by marco-santulli** [nocodb/nocodb#838] [Q&A] [answered]
Hi,

I can't find a way to use an external database for metadata that is protecded by SSL.  I am currently using a postgres DB, I start nocodb with docker, passing in an environment URL like:
-e NC_DB="pg://la.........

how can I pass in the SSL certificate and the fact that the DB is SSL required?

M

**Comment by AlfredoRamos** [comment]
I'm using the `DATABASE_URL` environment variable to set the PostgreSQL DSN instead of `NC_DB`, as stated in [the docs](https://docs.nocodb.com/getting-started/installation#environment-variables).

If it helps, in my `docker-compose.yml` file I have something similar:

```yaml
services:
  nocodb:
    image: nocodb/nocodb:latest
    restart: always
    environment:
      DATABASE_URL: postgres://dbuser:dbpassword@db:5432/dbname?sslmode=require
    depends_on:
      - db
```

Then on my PostgreSQL service:

```yaml
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ssl/server.crt:/var/lib/postgresql/server.crt
      - ./ssl/server.key:/var/lib/postgresql/server.key
```

Of course, you'll need to replace `dbname`, `dbuser`, `dbpassword` and the path for your SSL certificate files.
