### DISCUSSION TITLE
🐛 Bug: Meta database configuration missing database name

### DISCUSSION THREAD

**Discussion by 0195b3a7cb6735967a8f** [nocodb/nocodb#8966] [Q&A] [answered]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

<details>
<summary>Copy this <code>docker-compose.yaml</code></summary>

```yaml
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: nocodb,app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    networks:
      - internal

  nocodb:
    depends_on:
      postgres:
        condition: service_healthy
    image: "nocodb/nocodb:latest"
    restart: unless-stopped
    ports:
      - "9080:8080"
    environment:
      NC_DB: "pg://postgres:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}?d=nocodb"
    volumes:
      - ./data/nocodb:/usr/app/data
    networks:
      - internal
      - exposed

networks:
  internal:
    driver: bridge
    internal: true
  exposed:
    driver: bridge
```

</details>

<details>
<summary>Copy this <code>multiple-databases.sh</code></summary>

```sh
#!/bin/bash

set -e
set -u

function create_user_and_database() {
    local database=$1
    echo "  Creating user and database '$database'"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $database WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
        CREATE DATABASE $database;
        GRANT ALL PRIVILEGES ON DATABASE $database TO $database;
EOSQL
}

if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
    echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
    for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        create_user_and_database $db
    done
    echo "Multiple databases created"
fi
```

</details>

<details>
<summary>Create a <code>.env</code></summary>

```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
```

</details>

Run `docker compose up`

You can see following Error:
```
nocodb-1    | [Nest] 8  - 07/08/2024, 11:24:31 AM   ERROR [ExceptionHandler] Error: Meta database configuration missing database name
nocodb-1    | Error: Error: Meta database configuration missing database name
nocodb-1    |     at NcConfig.create (/usr/src/app/docker/main.js:2:2091016)
nocodb-1    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nocodb-1    |     at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1724327)
nocodb-1    |     at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
nocodb-1    |     at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
nocodb-1    |     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
nocodb-1    |     at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
nocodb-1    |     at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
nocodb-1    |     at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
nocodb-1    |     at async Promise.all (index 3)
nocodb-1 exited with code 0
```

Even tho the `NC_DB` URI is correctly set:
```
root@vm1:/opt/Stack$ docker exec -it stack-nocodb-1 /bin/sh
/usr/src/app # echo $NC_DB
pg://postgres:5432?u=postgres&p=password?d=nocodb
/usr/src/app # exit
```

### Desired Behavior

NocoDB should start without any Problems

### Project Details

NocoDB running in Docker using Docker Compose
