### DISCUSSION TITLE
Docker nocodb Connect to Host MySQL?

### DISCUSSION THREAD

**Discussion by nickian** [nocodb/nocodb#902] [Q&A] [answered]
If I deploy nocodb using this and access it via nginx reverse proxy...

```
docker run -d -p 8080:8080 \
    -e NC_DB="mysql2://host.docker.internal:3306?u=root&p=password&d=d1" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    nocodb/nocodb:latest
```

How can I have the NC_DB variable use the Docker host machine's MySQL? I tried replacing `host.docker.internal` with `localhost` and that doesn't work. I want to be able to access MySQL databases that are on my normal MySQL installation (outside of docker).

**Comment by farzadpanahi** [comment]
did you find a solution?

**Comment by nickian** [comment, marked as answer]
Yes, this is what I have been using. I use a `docker-compose.yml` file instead:

```yml
version: "2.1"
services:
  nocodb:
    environment:
      NC_DB: "mysql2://host.docker.internal:3306?u=db_user&p=db_password&d=db_name"
      NC_PUBLIC_URL: https://nocodb-url.com
      NUXT_PUBLIC_NC_BACKEND_URL: https://nocodb-url.com
      NC_DISABLE_TELE: true
      NC_ALLOW_LOCAL_HOOKS: true
    image: "nocodb/nocodb:latest"
    ports:
      - "8092:8080"
    restart: always
    volumes:
      - "./nc_data:/usr/app/data"
    networks:
      custom_network:
        ipv4_address: 172.28.0.2 # This is the fixed IP for your container
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
```

I think I also had to add a rule to the to the firewall: `sudo ufw allow from 172.28.0.0/16 to any port 3306`
