### ISSUE TITLE
🐛 Bug: nocodb hitting traefik ratelimit

### ISSUE THREAD

**Issue by alfureu** [nocodb/nocodb#10310]
### Please confirm that the bug report does ***not*** already exist

- [x] I confirm there is no existing issue for this bug.

### Steps to reproduce

Setup a nocodb instance with traefik reverse proxy. Use the [ratelimit plugin](https://doc.traefik.io/traefik/middlewares/http/ratelimit/) with default settings:

```
# Here, an average of 100 requests per second is allowed.
# In addition, a burst of 200 requests is allowed.
http:
  middlewares:
    test-ratelimit:
      rateLimit:
        average: 100
        burst: 200
```

If enabled in the middleware chain, nocodb easily trigger this ratelimit with connections to the docker and the database (for some reason). I see errors 429 in the browser logs.

### Desired Behavior

Nocodb should not do this many connections, or somehow should address the ratelimit, which is a standard/minimal protection for reverse proxy.

### Project Details

```
NocoDB used as docker: true
NocoDB version: 0.260.2
Database used in NC_DB URL: pg
OS on which NocoDB is running: debian
Database version: 17
```
