### ISSUE TITLE
🐛 Bug: Deserialization Error on Minio plugin - fresh upstall

### ISSUE THREAD

**Issue by jpbourgeon** [nocodb/nocodb#10332]
### Please confirm that the bug report does ***not*** already exist

- [x] I confirm there is no existing issue for this bug.

### Steps to reproduce

I can't make minio work on my instance behind an nginx reverse-proxy.

Nocodb works fine but the Minio plugin throws :
```
{
    "msg": "char '4' is not expected.:1:1\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object."
}
```

Nocodb is installed with the upstall script : subdomain for nocodb and minio (nocodb-s3), both without a certificate. Nginx handles the certificates.

@DarkPhoenix2704 may I ask for your assistance ?

### Desired Behavior

Nocodb should be able to talk to a minio storage instance through a reverse-proxy gracefully.

### Project Details

Node: **v22.13.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.260.2**

**Comment by jpbourgeon** [comment]
I installed with the upstall script, changed the URLs in docker.env and started/stopped the stack manually with docker-compose commands.

docker.env :
```shell
POSTGRES_DB=nocodb
POSTGRES_USER=postgres
POSTGRES_PASSWORD=*****
NC_DB=pg://db:5432?d=nocodb&user=postgres&password=*****
REDIS_PASSWORD=*****
NC_REDIS_URL=redis://:*****@redis:6379/0
MINIO_ROOT_USER=*****
MINIO_ROOT_PASSWORD=*****
NC_S3_BUCKET_NAME=nocodb
NC_S3_REGION=us-east-1
NC_S3_ACCESS_KEY=*****
NC_S3_ACCESS_SECRET=*****
NC_S3_FORCE_PATH_STYLE=true
NC_S3_ENDPOINT=https://nocodb-s3.cdg71.fr
NC_PUBLIC_URL=https://nocodb.cdg71.fr
```
docker-compose.yml
```yaml
services:
  nocodb:
    image: nocodb/nocodb:latest
    env_file: docker.env
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db
      - redis
      - minio
    restart: unless-stopped
    volumes:
      - ./nocodb:/usr/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.nocodb.rule=Host(`nocodb.cdg71.fr`)"
      - "traefik.http.routers.nocodb.entrypoints=web"
    networks:
      - nocodb-network
  db:
    image: postgres:16.6
    env_file: docker.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nocodb-network
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.minio.address=:9000"
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    depends_on:
      - nocodb
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nocodb-network

  redis:
    image: redis:latest
    restart: unless-stopped
    env_file: docker.env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "--raw", "incr", "ping" ]
    volumes:
      - ./redis:/data
    networks:
      - nocodb-network
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    env_file: docker.env
    entrypoint: /bin/sh
    volumes:
      - ./minio:/export
    command: -c 'mkdir -p /export/nocodb && /usr/bin/minio server /export'
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.rule=Host(`nocodb-s3.cdg71.fr`)"
      - "traefik.http.routers.minio.entrypoints=web"
    networks:
      - nocodb-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 2 * * 6" --cleanup
    restart: unless-stopped
    networks:
      - nocodb-network

volumes:
    redis:
networks:
  nocodb-network:
    driver: bridge
```
