### ISSUE TITLE
[Feature] Automate creation of tables (via Rest API / JSON / Yaml...)

### ISSUE THREAD

**Issue by richnourichnou** [nocodb/nocodb#1430]
It would be interesting to be able to create the tables automatically.

Of course, only for "simple" fields (not links, formulas...).

With a rest api, or maybe a yaml...

```
createtable:
    name: pizzas
    columns:
        column:
            name: name
            type: String
        column:
            name: ingredients
            type: LongString
        column:
            name: price
            type: Numbrer
```

Of course, importing a JSON file to create/fill data could be great...
