### ISSUE TITLE
[Cannot read property 'meta' of undefined] When create table

### ISSUE THREAD

**Issue by geosmart** [nocodb/nocodb#1452]
**Please enter the following details**

use nocodb with docker-compose
```yaml
version: '3'
services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    network_mode: "host"
    environment:
      - NC_DB=mysql2://0.0.0.0:3306?u=root&p=xxx&d=nocodb
      - PORT=18180
```

create a project ,it's ok.
but when create a table ,throws 
```js
POST /dashboard/?q=sqlOpPlus_tableCreate 403 21 - 5.832 ms
select * from `nc_disabled_models_for_role` where `project_id` = 'nocodb_bigt' and `db_alias` = 'db' and ((`relation_type` = 'hm' and `rtn` = 'nc_bigt__user') or (`relation_type` = 'bt' and `tn` = 'nc_bigt__user'))
TypeError: Cannot read property 'meta' of undefined
    at o.tableXcModelGet (/usr/src/app/docker/main.js:2:96720)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async o.handleRequest (/usr/src/app/docker/main.js:2:89856)
    at async /usr/src/app/docker/main.js:2:64165
POST /dashboard/?q=sqlOp_tableXcModelGet 400 50 - 13.714 ms
```

what's happen?  does something miss to config?
