### ISSUE TITLE
I can't change the default port 8080 to a custom value

### ISSUE THREAD

**Issue by patrykpalej** [nocodb/nocodb#1617]
I'm running nocodb using docker-compose, namely PostgreSQL docker-compose. I want to run it on another port than the default 8080 so in the `ports` section I changed it to:

```
 ports:
      - "8090:8090"
```
I also added an environment variable in the proper section:
```
 environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: root_db
      PORT: 8090
```

Unfortunately running the app on port 8090 doesn't work, I get "This site can’t be reached" in my browser. Is it possible to change the default port?
