### ISSUE TITLE
DockerFile ENV admin_user

### ISSUE THREAD

**Issue by raphaelauv** [nocodb/nocodb#221]
I would like to define the admin_user with a ENV 

so I could run in my local dev stack (docker-compose)

```yaml
  db_ui:
    image: nocodb/nocodb
    environment:
      ADMIN_USER: toto
      ADMIN_PASSWORD: security
    ports:
      - 4041:8080
```

Where can I find the dockerfile and a way to programmatically define the admin user ?
