### ISSUE TITLE
Docker-compose mysql not working

### ISSUE THREAD

**Issue by elvus** [nocodb/nocodb#2282]
Docker compose mysql status unhealty
```
NocoDB used as docker : true
NocoDB version : latest
Database used in NC_DB URL  : mysql
```
![imagen](https://user-images.githubusercontent.com/24416449/172493186-79f6532e-2f43-4746-a9c3-2e2150b8a24b.png)

**Comment by elvus** [comment]
I solved it updating the file
```
version: '2.1'

services:
  root_db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
#    below line shows how to change charset and collation
#    uncomment it if necessary
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root_db
      MYSQL_USER: noco
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - nc_data:/usr/app/data
    environment:
      NC_DB: "mysql2://root_db:3306?u=noco&p=password&d=root_db"
volumes:
  db_data: {}
  nc_data: {}
```
