### ISSUE TITLE
Wrong routing if using NocoDB behind Traefik

### ISSUE THREAD

**Issue by mdebic** [nocodb/nocodb#3098]
Hi, 

I am setting up NocoDB behind Traefik as reverse proxy. I attached my working docker-compose.yaml below. The issue I am having is, that I can not create a user, an therefore cannot login. Neither the option below by passing the NC_ADMIN_EMAIL and _PASSWORD env variables works, nor the sentence "You will be the Super Admin user" does appear when I access the sign up site for the first time. When I still try to create a user, the loading button just keeps spinning forever and nothing happens. The logs of the NocoDB container do not show anything happening, I can not find any error message in any of the running containers. Maybe it is worth mentioning, that I am running my setup within a network behind a proxy. I could not find any related issues, hope someone has a solution.

```
version: '3'

networks:
  traefik-services:
    driver: bridge

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.8
    networks:
      - traefik-services
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nocodb:
    container_name: nocodb
    networks: [traefik-services]
    volumes:
      - '/opt/traefik/nocodb:/usr/app/data/'
    expose:
      - 8080
    environment:
      - "NC_DB=pg://nocodb_db:5432?u=postgres&p=password&d=root_db"
      - "NC_AUTH_JWT_SECRET=569a1821-0a93-45e8-87ab-eb857f20a010"
      - "NC_DASHBOARD_URL=/nocodb"
      - "NC_PUBLIC_URL=http://localhost"
      - "NC_INVITE_ONLY_SIGNUP=true"
      - "NC_ADMIN_EMAIL=somemail@domain.de"
      - "NC_ADMIN_PASSWORD=!Password1234"
      - "NC_CONNECT_TO_EXTERNAL_DB_DISABLED=false"
      - "NC_DISABLE_TELE=true"
    image: 'nocodb/nocodb:latest'
    labels:
      - traefik.enable=true
      - traefik.http.routers.nocodb.rule=PathPrefix(`/nocodb`)
      - traefik.http.services.nocodb.loadbalancer.server.port=8080
      - traefik.http.routers.nocodb.entrypoints=http
      
  nocodb_db:
    container_name: nocodb_db
    networks: [traefik-services]
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - /opt/traefik/nocodb_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: root_db
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
```
