### ISSUE TITLE
[API] Get Return 400 after some time

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#3767]
```
NocoDB used as docker : true
NocoDB version : 0.92.4
Database used in NC_DB URL  :  pg 
Project was created  by clicking :  New Project by connecting to external database Postgresql
```

**Steps To Reproduce**

1. Create new projet from an existing postgresql database
2. Generate an API token
3. Call an generated API  from my project : GET api/v1/db/data/v1/<PROJET>/<TABLE>/views/<Views_name>
4. First i get Http 200
5. After some times (2 hours or less), I get an HTTP 400. After 1 or 2 more attemps, I get an 200

See the log : 

`
Connection Error: Connection ended unexpectedly
A :: Error: select ...<SOME_FIELD> from "<TABLE>" where (((("siret" in (select "__nc0"."code" from "ref_siret" as "__nc0" where "__nc0"."code_commune" = '56162')) and ("montant" > '0')))) limit 25 - read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
`

**Comment by o1lab** [comment]
Where are you running the server and database ? Looks like the connection is ending for some reason - it could be your database or server is serverless ?

**Comment by syji35** [comment]
nocodb and postgres running on Docker Swarm.    
Neither of them stop

**Comment by syji35** [comment]
Here my service postres : 

```
version: '3.7'

networks:
  default:
    external: true
    name: app_network

volumes:
  pg_data:
    driver: local

services:
  postgres:
    image: postgres:14.5-alpine
    ports:
      - "60145:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xxxxxxxxxxxx
      POSTGRES_USER: postgres
      POSTGRES_DB: nocodb
    deploy:
      restart_policy:
        max_attempts: 2
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
        constraints:
          - "node.labels.data==true"
  ```
