### ISSUE TITLE
🐛 Bug: Migration table is already locked with maridb 10.7.3

### ISSUE THREAD

**Issue by djaffer** [nocodb/nocodb#4844]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Try to run on latest mariadb nocodb with docker-compose. Is this even tested with Mariadb 10.7.3? 

Sometimes I get this 
```
nocodb  | Visit -> http://localhost:8080/dashboard
nocodb  | Can't take lock to run migrations: Migration table is already locked
nocodb  | If you are sure migrations are not running you can release the lock manually by running 'knex migrate:unlock'
nocodb  | MigrationLocked: Migration table is already locked
nocodb  |     at /usr/src/app/node_modules/knex/lib/migrations/migrate/Migrator.js:342:13
nocodb  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb  |     at async Migrator._runBatch (/usr/src/app/node_modules/knex/lib/migrations/migrate/Migrator.js:358:7)

```

Now I try to delete all database files and recreate database.

```
nocodb  | Visit -> http://localhost:8080/dashboard
nocodb  | migration file "nc_011" failed
nocodb  | migration failed with error: alter table `nc_audit_v2` add index `nc_audit_v2_row_id_index`(`row_id`) - Connection lost: The server closed the connection.
nocodb  | Error: ROLLBACK - Can't add new command when connection is in closed state
nocodb  |     at Connection._addCommandClosedState (/usr/src/app/node_modules/mysql2/lib/connection.js:148:17)
nocodb  |     at Connection.query (/usr/src/app/node_modules/mysql2/lib/connection.js:546:17)
nocodb  |     at /usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:132:18
nocodb  |     at new Promise (<anonymous>)
nocodb  |     at Client_MySQL2._query (/usr/src/app/node_modules/knex/lib/dialects/mysql/index.js:126:12)
nocodb  |     at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17) nocodb  |     at Client_MySQL2.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)
nocodb  |     at /usr/src/app/node_modules/knex/lib/execution/transaction.js:363:24
nocodb  |     at new Promise (<anonymous>)
nocodb  |     at Client_MySQL2.trxClient.query (/usr/src/app/node_modules/knex/lib/execution/transaction.js:358:12) {
nocodb  |   fatal: true
nocodb  | }
```

### Desired Behavior

It should work

### Project Details

```
version: "3"
services:
  database:
    container_name: database
    image: mariadb:latest
    env_file:
      - ./config/development.env
    networks:
      - network
    restart: always
    volumes:
      - ./data/database:/var/lib/mysql
      
  nocodb: 
    container_name: nocodb
    depends_on: 
    - database
    env_file:
      - ./config/development.env
    image: "nocodb/nocodb:latest"
    ports: 
      - "8082:8080"
    networks:
      - network
    restart: always
    volumes: 
      - "./data/nocodb:/usr/app/data"

networks:
  network:
    external: true
```
