### ISSUE TITLE
🐛 Bug: Division in formula display 'Invalid Formula'

### ISSUE THREAD

**Issue by chxp** [nocodb/nocodb#4929]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### The data is: 
![Screenshot_20230126_135026](https://user-images.githubusercontent.com/14882692/214767320-761a255d-85a9-4349-81c3-517d3d2fd47a.png)

![Screenshot_20230126_134102](https://user-images.githubusercontent.com/14882692/214767346-d62d67ec-3aab-4897-8f80-3fd07c4f2d37.png)

### The formula and error message is:
![Screenshot_20230126_134137](https://user-images.githubusercontent.com/14882692/214767395-277ac2f1-aca4-4107-b84a-2a67316ac077.png)

### The minus/plus works fine:
![Screenshot_20230126_134328](https://user-images.githubusercontent.com/14882692/214767565-15636295-08f2-41bd-ba18-061fe8d08c9d.png)

Interestingly, I meet the problem of division in at least three releases. Is it a platform-based problem?

The information of nocodb:
Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.101.2**

The compose file I use:
```
version: "2.1"
services: 

  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "mysql2://root_db:3306?u=noco&p=passwordcxxp12&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - "8300:8080"
    restart: always
    volumes: 
      - "/home/xxp/apps/nocodb/data/nc_data:/usr/app/data"

  root_db: 
    environment: 
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: pa12
      MYSQL_ROOT_PASSWORD: pa12
      MYSQL_USER: noco
    healthcheck: 
      retries: 10
      test: 
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:5.7"
    restart: always
    volumes: 
      - "/home/xxp/apps/nocodb/data/db_data:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

My OS is `ubuntu 20.04.5 LTS`:
```
~$ uname -a
Linux VM-20-12-ubuntu 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64
 GNU/Linux                                                                                             
```

For the previous problem see https://github.com/nocodb/nocodb/issues/4527

### Desired Behavior

division works fine.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.101.2**
