### ISSUE TITLE
🐛 Bug: Using the Docker image with non-default port setting exposes port 8080 regardless

### ISSUE THREAD

**Issue by Bastlwastl42** [nocodb/nocodb#5351]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

minimal docker-compose file
```
version: "3.8"

services:
  noco_front:
    depends_on:
      root_db:
        condition: service_healthy
    environment:
      NC_DB: "pg://${POSTGRES_DB}:${POSTGRES_PORT}?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}"
      NC_DISABLE_TELE: "true"
      PORT: ${REVIEW_TOOL_PORT}
      NC_ADMIN_EMAIL: ${ADMIN_MAIL}
      NC_ADMIN_PASSWORD: ${ADMIN_PW}
    image: "nocodb/nocodb:0.105.3"
    ports:
      - ${REVIEW_TOOL_PORT}:${REVIEW_TOOL_PORT}
    volumes:
      - "nc_data:/usr/app/data"

  root_db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres:12
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}


volumes:
  db_data:
  nc_data:
```

with minimal `.env` file

```
POSTGRES_DB=root_db
POSTGRES_PASSWORD=password
POSTGRES_USER=postgres
POSTGRES_PORT=5432
REVIEW_TOOL_PORT=7272
ADMIN_MAIL=admin@admin.admin
ADMIN_PW=super_secret
```
run with simple `docker-compose up -d` command in a folder with both files. Observe exposed ports with `docker ps`command:
<img width="857" alt="Screenshot 2023-03-23 at 11 27 22" src="https://user-images.githubusercontent.com/45485100/227175556-37c04142-6f3a-4210-a93e-0f51b348d258.png">

### Desired Behavior

The nocodb container only exposes the port set by the environment variable 'PORT' as described [here](https://docs.nocodb.com/getting-started/environment-variables) and none further.

### Project Details

Use as docker: true
nocooDB version: 0.105.3
Database used: here Postgres, but I claim this Is independent from the used db type. 
This is not a project or spreadsheet related issue.
OS Running: Docker on MacOS or Ubuntu
NodeJS Version as given in Docker
DatabaseVersion: posgresql:12
