### ISSUE TITLE
🐛 Bug: Google Cloud Storage Plugin Private Key exceeds character limit

### ISSUE THREAD

**Issue by cthai18** [nocodb/nocodb#5606]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Install nocodb with docker via the command in the documentation
2. Setup Google cloud storage bucket, and download Private key for Google Cloud service account that has appropriate read/write permissions for cloud storage
3. Open NocoDB App store and click install on google cloud storage plugin
4. Input the bucket name, client email, private key, and project id
5. Click "Test" -- notification with green check mark pops up that says "Successfully tested plugin settings". In addition, logs show 200 response "POST /api/v1/db/meta/plugins/test 200 4 - 118.114 ms"
6. Click "Save" -- notification with red X pops up that says "/input - must NOT have more than 255 characters, /input - must be null, /input - must match exactly one schema in oneOf". Logs show the following:

`
      message: 'must NOT have more than 255 characters'
    },
    {
      instancePath: '/input',
      schemaPath: '#/components/schemas/StringOrNull/oneOf/1/type',
      keyword: 'type',
      params: [Object],
      message: 'must be null'
    },
    {
      instancePath: '/input',
      schemaPath: '#/components/schemas/StringOrNull/oneOf',
      keyword: 'oneOf',
      params: [Object],
      message: 'must match exactly one schema in oneOf'
    }
  ]
}
PATCH /api/v1/db/meta/plugins/nc_gy9qb6tvegjdbx 400 568 - 10.866 ms`

### Desired Behavior

The plugin successfully saves my cloud storage configuration, and I can upload attachments without an error.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.106.1**

**Comment by cthai18** [comment]
The error log got cut off, here's the full log:

p :: d [Error]: Invalid request body
    at Function.ajvValidationError (/usr/src/app/docker/main.js:1:21237)
    at t.validatePayload (/usr/src/app/docker/main.js:1:1443260)
    at Object.t.pluginUpdate (/usr/src/app/docker/main.js:1:1803535)
    at p (/usr/src/app/docker/main.js:1:1993540)
    at /usr/src/app/docker/main.js:1:14824
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at /usr/src/app/docker/main.js:1:27640
    at /usr/src/app/docker/main.js:1:14824
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) {
  errors: [
    {
      instancePath: '/input',
      schemaPath: '#/components/schemas/StringOrNull/oneOf/0/maxLength',
      keyword: 'maxLength',
      params: [Object],
      message: 'must NOT have more than 255 characters'
    },
    {
      instancePath: '/input',
      schemaPath: '#/components/schemas/StringOrNull/oneOf/1/type',
      keyword: 'type',
      params: [Object],
      message: 'must be null'
    },
    {
      instancePath: '/input',
      schemaPath: '#/components/schemas/StringOrNull/oneOf',
      keyword: 'oneOf',
      params: [Object],
      message: 'must match exactly one schema in oneOf'
    }
  ]
}
PATCH /api/v1/db/meta/plugins/nc_gy9qb6tvegjdbx 400 568 - 11.302 ms

**Comment by fahmimmaliki** [comment]
I face the same issue in version **0.106.1** and **0.107.0-beta.latest**. In version **0.105.3**, I was able to successfully configure Google Cloud Storage using the same private key that I am using now. However, in versions **0.106.1** and **0.107.0-beta.latest**, I receive an error message stating that `/input - must NOT have more than 255 characters, /input - must be null, /input - must match exactly one schema in oneOf` when inputting the same private key. There may be a bug in the newer application versions' configuration process for Google Cloud Storage. Please don't hesitate to let me know if there is any additional information that I can provide to help resolve this issue. Thank you!

I run nocodb with docker compose
here is my `docker-compose.yml`
```yaml
version: '2.1'
services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
    image: "nocodb/nocodb:0.105.3"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  root_db: 
    environment: 
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres:12
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - "db_data:/var/lib/postgresql/data"
volumes: 
  db_data: {}
  nc_data: {}
```
