### ISSUE TITLE
🐛 Bug: no connection to a Postgresql DB in a docker

### ISSUE THREAD

**Issue by Productivix** [nocodb/nocodb#5616]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

create a docker with PostgreSql : 
ex docker-compose.yml : 
 ```
 db:
   image: "postgres"
   restart: always
   environment:
     POSTGRES_USER: william
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: essaiventes
  
   ports:
     - "5438:5432"
   volumes:
    - "./postgres-data:/var/lib/postgresql/data"
    - "./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
    - "./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql"
```
take the tables and data from https://github.com/jdaarevalo/docker_postgres_with_data
test with DBeaver 23.0.4 that you can connect to the DB and see the schema : yes 
install a node server : as https://github.com/nocodb/nocodb-seed
attach the DB as in DBeaver : yes you can 
But you cannot see the schema ! nor the tables  !

### Desired Behavior

see the tables and the schema of the DB

### Project Details

NocoDB : 106.1
on Linux debian 10
last postGreSql
