### ISSUE TITLE
🐛 Bug: Missing Refresh Token

### ISSUE THREAD

**Issue by prononext** [nocodb/nocodb#5978]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I got the following error log in my docker service nocodb:0.109.2

```[Nest] 11  - 06/28/2023, 6:58:48 AM   ERROR [i] Missing refresh token
Error: Missing refresh token
    at Function.badRequest (/usr/src/app/docker/main.js:1:652307)
    at k.refreshToken (/usr/src/app/docker/main.js:1:1251281)
    at j.refreshToken (/usr/src/app/docker/main.js:1:174433)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17```

### Desired Behavior

Working error free on docker logs

### Project Details

0.109.2
Postgresql12
redis6

### Attachments

_No response_

**Comment by prononext** [comment]
is seemes that this error has to do with Redis. Because when deactivating Redis the error is gone.

I get a very strange behavior like: 

### Creating a new project
The project dissapears on the homescreen and comes back randomly.

### Creating tables inside a project
The table dissapear and come back randomly. They get created definately because creating them again, gives an error that already existent. 

```
  redis:                                     
    image: rapidfort/redis6-ib
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "$$REDIS_PASSWORD"]
    environment:
      REDIS_PASSWORD: "/run/secrets/REDIS_PASSWORD"
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - nocodb      
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure    
```

The service has the standard logs on starting and then nothing more: 
```
1:C 28 Jun 2023 07:42:59.857 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 28 Jun 2023 07:42:59.857 # Redis version=6.2.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 28 Jun 2023 07:42:59.857 # Configuration loaded
1:M 28 Jun 2023 07:42:59.857 * monotonic clock: POSIX clock_gettime
1:M 28 Jun 2023 07:42:59.858 * Running mode=standalone, port=6379.
1:M 28 Jun 2023 07:42:59.858 # Server initialized
1:M 28 Jun 2023 07:42:59.858 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 28 Jun 2023 07:42:59.858 * Ready to accept connections
```

Maybe it could be my fault on setting up the redis service. The connection was successfull, I know because I first got the connection wrong. 

Any advice would be really nice.
