### ISSUE TITLE
🐛 Bug: Can not add values to foreign key columns of external tables.

### ISSUE THREAD

**Issue by MrChadMWood** [nocodb/nocodb#6562]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Issue: Using an external Postgres database as the data source. Foreign key columns can not have values added to them. This prevents the creation of new rows.

1. Create docker-compose.yml
```
version: '3.5'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER: "postgres"
      - POSTGRES_PASSWORD: "password"
      - PGDATA: "/data/postgres"
    volumes:
      - ./postgres_data/:/data/postgres
      - ./create_database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - 8080:8080
    environment:
      - NC_DB: "pg://metastore:5432?u=postgres&p=password&d=nocodb_metastore"
      - NC_PUBLIC_URL: "http://localhost"
    depends_on:
      metastore:
        condition: service_healthy
    restart: always
    volumes:
      - nc_data:/usr/app/data
    networks:
      - postgres

  metastore: 
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB: nocodb_metastore
      - POSTGRES_PASSWORD: password
      - POSTGRES_USER: postgres
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    restart: always
    volumes: 
      - db_data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    db_data:
    nc_data:
```

2. Create file `./create-database.sql` in same directory as docker-compose. Contents being:
```
CREATE DATABASE lineitem101;

\c lineitem101

CREATE TABLE IF NOT EXISTS cost_type (
    name VARCHAR PRIMARY KEY,
    label VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS cost_code (
    label VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS unit_of_measure (
    name VARCHAR PRIMARY KEY,
    label VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS job (
    name VARCHAR PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS subjob (
    name VARCHAR PRIMARY KEY,
    label VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS subitem (
    name VARCHAR PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS lineitem (
    id SERIAL PRIMARY KEY,
    job VARCHAR NOT NULL,
    subjob VARCHAR NOT NULL,
    cost_code VARCHAR NOT NULL,
    cost_type VARCHAR NOT NULL,
    subitem VARCHAR NOT NULL,
    unit_of_measure VARCHAR NOT NULL,
    date DATE NOT NULL,
    cost_per_measure INT NOT NULL,
    note VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(job) REFERENCES job(name),
    FOREIGN KEY(subjob) REFERENCES subjob(name),
    FOREIGN KEY(cost_code) REFERENCES cost_code(label),
    FOREIGN KEY(cost_type) REFERENCES cost_type(name),
    FOREIGN KEY(subitem) REFERENCES subitem(name),
    FOREIGN KEY(unit_of_measure) REFERENCES unit_of_measure(name)
);

CREATE INDEX IF NOT EXISTS idx_lineitem_job ON lineitem(job);
CREATE INDEX IF NOT EXISTS idx_lineitem_date ON lineitem(date);
CREATE INDEX IF NOT EXISTS idx_lineitem_subitem ON lineitem(subitem);
CREATE INDEX IF NOT EXISTS idx_lineitem_costtype ON lineitem(cost_type);
CREATE INDEX IF NOT EXISTS idx_lineitem_costcode ON lineitem(cost_code);
CREATE INDEX IF NOT EXISTS idx_lineitem_costtype_subitem ON lineitem(cost_type, subitem);
CREATE INDEX IF NOT EXISTS idx_lineitem_costcode_subitem ON lineitem(cost_code, subitem);
CREATE INDEX IF NOT EXISTS idx_lineitem_costcode_costtype ON lineitem(cost_code, cost_type);
```

3. Launch. Use credentials found within the docker-compose file to connect to the `postgres1` image as a data source
4. Fill each table (except lineitem) with some sample data
5. Attempt to create a row in the lineitem table

### Desired Behavior

A row should be entered as expected.

### Project Details

NocoDB used as Docker: True

### Attachments

![image](https://github.com/nocodb/nocodb/assets/90083658/82fe4d95-c7b8-425f-bdb3-1a8a8633ae25)
