### ISSUE TITLE
🐛 Bug: Additional property DB_QUERY_LIMIT_MAX is not allowed

### ISSUE THREAD

**Issue by yourtrashistrash** [nocodb/nocodb#6790]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Getting the when adding DB_QUERY_LIMIT_MAX to environment variables: 

\nocodb\docker-compose\mysql\docker-compose.yml: services.root_db Additional property DB_QUERY_LIMIT_MAX is not allowed

root_db: 
    environment: 
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: noco
    DB_QUERY_LIMIT_MAX: 1000
    healthcheck: 
      retries: 10
      test: 
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:8.0.32"
    restart: always
    volumes: 
      - "db_data:/var/lib/mysql"
#    below line shows how to change charset and collation
#    uncomment it if necessary
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

### Desired Behavior

showing 1000 rows. 

### Project Details

Nocodb docker: true
Version: Latest

**Comment by wingkwong** [comment]
You should put `DB_QUERY_LIMIT_MAX` undewr `nocodb.environment`

```
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "mysql2://root_db:3306?u=noco&p=password&d=root_db"
      DB_QUERY_LIMIT_MAX: 1000
    image: "nocodb/nocodb:latest"
```
