### ISSUE TITLE
🐛 Bug: NotFoundException: Cannot GET /plugins/ovhCloud.png

### ISSUE THREAD

**Issue by geekyouth** [nocodb/nocodb#6840]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![image](https://github.com/nocodb/nocodb/assets/12899262/6e1ad751-295e-49b3-b026-2e10392a553b)

### Desired Behavior

picture should  preview

### Project Details

```yaml
services:
  nocodb:
    image: nocodb/nocodb:0.202.5
    hostname: nocodb
    container_name: nocodb-dev
    environment:
      NC_DB: "mysql2://mysql57:3306?u=nocodb_dev&p=nocodb_dev&d=nocodb_dev"
      TZ: Asia/Shanghai
      NC_ATTACHMENT_FIELD_SIZE: 500MB
    ports:
      - "2380:8080"
    restart: unless-stopped
    volumes:
      - ./_docker-data/nc_data:/usr/app/data
    networks:
      fullstack:

```

### Attachments

![image](https://github.com/nocodb/nocodb/assets/12899262/fb3253b7-19d7-4b96-a5ae-0ac3744b9dfc)
