### ISSUE TITLE
🐛 Bug: Date filtering result - one day behind in MSSQL

### ISSUE THREAD

**Issue by felipebossolani** [nocodb/nocodb#7029]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm facing a problem with dates on Nocodb. All dates fields are showing/filtering one day behind. I check my configs and I dont know what is going on. Is it a bug or some mistake made by me?

docker-compose.yml (with TZ environment set):
```
version: '3'

services:
  nocodb:
    environment:
      - TZ=America/Cuiaba
      - NCC_DB=mssql://root_db:1433?u=sa&p=Password123.&d=root_db
    image: nocodb/nocodb:latest
    restart: always
    volumes:
      - nc_data:/usr/app/data
    networks:
      - frontend

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - nocodb
    networks:
      - frontend

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - frontend

networks:
  frontend:

volumes: 
  db_data: {}
  nc_data: {}

```
Database (MSSQL) query a timezone config:
<img width="688" alt="image" src="https://github.com/nocodb/nocodb/assets/24377387/b05ab426-fe48-4d11-98ad-590f7ce0c7f4">

Nocodb filter: 
<img width="591" alt="image" src="https://github.com/nocodb/nocodb/assets/24377387/8cbd7cf6-8f39-459d-b617-b7d8ea6d6b2e">

Nocodb Result:
<img width="706" alt="image" src="https://github.com/nocodb/nocodb/assets/24377387/803c2d7c-75fe-437b-b374-9eb7937c408e">

### Desired Behavior

Date filter respecting date that I chose.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.202.7**
