### ISSUE TITLE
🐛 Bug: copy record url in detail view not working

### ISSUE THREAD

**Issue by HelloGithubUniverse** [nocodb/nocodb#7117]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Open detail view of a record
- Click „Copy record url“
- Nothing happens…

### Desired Behavior

Url is copied to Clipboard.

### Project Details

202.8
linux arm

**Comment by HelloGithubUniverse** [comment]
Sorry…Yes button is changing Text. Nothing happens, no error log.
I can reproduce it also with Version 202.8, docker, windows server, edge browser
and found one more thing (similar, but Not the same):
- Share a Table
- Enable Public Viewing
- Click on „Copy URL“ -> nothing happens
- Log error: TypeError: cannot read properties of undefined (reading „writeText“) - entry.ef8d6884.js:1

**Comment by dstala** [comment]
@HelloGithubUniverse See if its related to below issue? Let us know here if it helps. 

https://github.com/nocodb/nocodb/issues/5333#issuecomment-1938604239

**Comment by HelloGithubUniverse** [comment]
Unfortunately, I cannot currently verify whether there is a connection. However, I suspect a different problem due to the error message.

**Comment by dstala** [comment]
@HelloGithubUniverse Does this issue persist still with latest version of NocoDB?

**Comment by Rannddyyy** [comment]
Hi @dstala, I still meet this issue in version 0.251.2.

Here are my steps and evironment:

### Steps

1. Go to any table with some records
2. Open any record's detail view
3. Click "Copy Record URL" button
4. "Ctrl+V" at any text field

### Observed Result

The button shows a message "Copied Record URL". However, when I try to paste (Ctrl+V) into any text field (e.g., the browser's address bar), it pastes the content I copied previously instead of the record's URL.

![detail-view-copied](https://github.com/user-attachments/assets/0e6d3cb2-3876-48f7-9fc1-4b8c1c2c4acc)

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.251.2**

Browser: Edge (126.0.2592.113), Firefox (128.0.2)
NocoDB accessed via HTTP with IP address or domain name, i.e., http://{server-ip}:8080 or http://{domain-name}:8080

<details>
<summary>Contents of <code>docker-compose.yml</code></summary>

```
version: '2.1'
services:
  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    environment:
      NC_DB: "pg://root_db:5432?u=postgres&p=${POSTGRES_PASSWORD}&d=root_db"
    image: "nocodb/nocodb:0.251.2"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "nc_data:/usr/app/data"
  root_db:
    environment:
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db_data/'
  nc_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './nc_data/'
```
</details>


### Additional Information

-  The logged-in user's access permission is "Organization Level Creator".
  ![Users-Management](https://github.com/user-attachments/assets/eb52ff94-d413-4805-a981-7d8fe13257de)
- The user role in the database is "Creator".
  ![database-role](https://github.com/user-attachments/assets/122d84a4-6186-4333-8e3e-f5331db214b8)

Please contact me if you require additional details. Looking forward to your reply.
