### ISSUE TITLE
🔦 Feature: support read-only and non-root docker containers

### ISSUE THREAD

**Issue by tcurdt** [nocodb/nocodb#8347]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

For security reasons some companies require containers to be run as non-root and sometimes even in read-only mode. This usually is no bigger problem but nocodb seems to have a very unusual docker setup.

Setting this should work without bigger problems:

```
services:
  nocodb:
    container_name: nocodb
    image: nocodb/nocodb:latest
    read_only: true
    user: 65534:65534
```

### Suggested Solution

TBH I am not quite sure why an un-tar would be necessary at container startup at runtime over build time.
If possible the image should be setup correctly at build time.

And if some folders need special permissions this here could be a work around:

```
ENV UID 65534
ENV GID 65534
RUN chown -R $UID:$GID /some/folder
```
