### ISSUE TITLE
🐛 Bug: NotFoundException: Cannot GET /dashboarddashboard/

### ISSUE THREAD

**Issue by schobernoise** [nocodb/nocodb#8443]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I cloned the github repo and cd'd into mysql. Then I edited the docker-compose.yml file to look somewhat like this:

```
version: "2.1"
services:
  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    environment:
      NC_DB: "mysql2://root_db:3306?u=noco&p=password&d=root_db"
      NC_PUBLIC_URL: https://example.com
      VIRTUAL_HOST: noco.example.com
    image: "nocodb/nocodb:latest"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "nc_data:/usr/app/data"
  root_db:
    environment:
      MYSQL_DATABASE: nocodb
      MYSQL_PASSWORD: H4PnLDfx7gdfdgdfgdfgyLuUEpgfgfDABh
      MYSQL_ROOT_PASSWORD: gA9Wksdfsdfsdfsdf6PJ%ghjjj!u
      MYSQL_USER: nocodb
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:8.3.0"
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
#    below line shows how to change charset and collation
#    uncomment it if necessary
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes:
  db_data: {}
  nc_data: {}
```

I configured my apache virtual host like this:

```
<VirtualHost *:80>
    ServerName noco.example.com
ServerAdmin mail@example.com
    ServerAlias www.noco.example.com
	# DocumentRoot /var/www/noco

    ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>


    RewriteEngine On
    # auto redirect HTTP to HTTPS
   Redirect permanent / https://noco.example.com/

	# auto redirect www to non-www
    <If "%{HTTP_HOST} == 'www.noco.example.com'">
        Redirect permanent / https://noco.example.com/
    </If>

     ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>

       	<Proxy *>
        	Require all granted
    	</Proxy>

	
	ProxyPreserveHost on
    	ProxyPass / http://127.0.0.1:8080/
    	ProxyPassReverse / http://127.0.0.1:8080/

        <Location />
          Order allow,deny
          Allow from all
        </Location>

</VirtualHost>


<VirtualHost *:443>
	ServerAdmin reach@fabianschober.com
	ServerName noco.example.com
	ServerAlias www.noco.example.com
    ServerAdmin reach@fabianschober.com

    ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>


    # auto redirect www to non-www
    <If "%{HTTP_HOST} == 'www.noco.example.com'">
        Redirect permanent / https://noco.example.com/
    </If>

    	# log files
    	ErrorLog /var/log/apache2/noco-error.log
    	CustomLog /var/log/apache2/noco-access.log combined

    	SSLEngine On
    	SSLCertificateFile /etc/letsencrypt/live/noco.example.com/fullchain.pem
    	SSLCertificateKeyFile /etc/letsencrypt/live/noco.example.com/privkey.pem

    <Location />
          Order allow,deny
          Allow from all
        </Location>

    	ProxyPreserveHost on
    	ProxyPass / http://127.0.0.1:8080/
    	ProxyPassReverse / http://127.0.0.1:8080/


</VirtualHost>
```

I made sure this is working fine.

Then I ran `docker compose up -d`, `docker ps -a` and `docker logs <container-id>`. At this piint, everything was green in the logs. Then I tried to access the site, and I always just get this error. 

### Desired Behavior

I should be able to access nocodb via the proxy.

### Project Details

NocoDB used with Docker, mysql variant, see details in the code above.

### Attachments

![image](https://github.com/nocodb/nocodb/assets/58608284/29f666aa-ac99-451a-bb97-4ffb77b2edb8)
![image](https://github.com/nocodb/nocodb/assets/58608284/4c66f9df-e9c6-47f4-bd09-3fed4242fd18)
