### ISSUE TITLE
🐛 Bug: The timezone of createdtime and updatedtime haven‘t been translate

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8593]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- I'm in +8:00 timezone, and I compared several time-type columns(time,datetime,formula, createdtime and updatedtime), maybe the timezone of createdtime and updatedtime are not translated
![image](https://github.com/nocodb/nocodb/assets/48933981/06f78c98-b2e8-4239-8a8d-5aeca0c03d3f)
- Here are the datas in the mysql DB.
![image](https://github.com/nocodb/nocodb/assets/48933981/0e88c05a-878e-421c-8785-2e3c90cf9635)
- 'DateTime' is right

### Desired Behavior

x

### Project Details

db: mysql
version:0.207.1
env:docker
timezone: UTC/GMT+08:00

**Comment by TangXY123** [comment]
- I notice that code translate some time-data to UTC format, maybe this make the time data shows in different standards. This makes us confused.
![image](https://github.com/nocodb/nocodb/assets/48933981/9a60430f-697e-4b44-8c7c-bb5984c3ebeb)

**Comment by TangXY123** [comment]
> @TangXY123 NocoDB relies on database timezone information. Can you confirm what is configured timezone for mysql in this case?
> 
> The information here might help https://stackoverflow.com/questions/930900/how-do-i-set-the-time-zone-of-mysql

Thank you for replies. 
I do those 2 tests:
**1. TZ of mysql is `Asia/Shanghai`.**
- In `docker-compose.yml`, modified the TZ of mysql to `Asia/Shanghai`.
```yml
version: "2.1"
services:
  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    environment:
      NC_DB: "mysql2://root_db:3306?u=nc&p=password&d=root_db"
      NC_DISABLE_AUDIT: 'true'
      NC_REDIS_URL: "redis://192.168.75.151:16380"
    image: "nocodb/nocodb:0.207.1"
    ports:
      - "8090:8080"
    restart: always
    volumes:
      - "/mydata/nc:/usr/app/data"
  redis_nc:
    image: "redis:latest"
    ports:
      - "16380:6379"
    restart: always
  root_db:
    environment:
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: nc
      MYSQL_INITDB_EXTRA_MY_CNF: |-
        [mysqld]
          group_concat_max_len = 1048576
     TZ: Asia/Shanghai
    privileged: true
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:latest"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "/mydata/db:/var/lib/mysql"
#    below line shows how to change charset and collation
#    uncomment it if necessary
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes:
  db_data: {}
  nc_data: {}
```
- Query the timezone of DB(It's 9:40 +08:00 indeed):
![image](https://github.com/nocodb/nocodb/assets/48933981/77f2b42e-6791-4238-b3b9-2c065a3f52ba)

- The time show in App(except the `time`, others including `formula-now`, `createdtime` and `lastmodifiedtime` are not correct.):
![image](https://github.com/nocodb/nocodb/assets/48933981/cf3f14cb-8edc-4957-914b-db7aad49c126)

**2. Without Setting the TZ of mysql.**
- Query the timezone of DB(time-difference is 8:00):
![image](https://github.com/nocodb/nocodb/assets/48933981/dd5ee2ee-e83e-4402-a29e-744f5ab74151)
- The time show in App, the differece is that the `formula` is not right now. `createdtime` and `modifiedtime` is 16 hours less than my localtime:
![image](https://github.com/nocodb/nocodb/assets/48933981/2cae7ab8-9e81-4f6a-bb2e-296160722d3d)
