### ISSUE TITLE
Gateway timeout with Traefik

### ISSUE THREAD

**Issue by Vercety87** [nocodb/nocodb#867]
NocoDB used as docker : true
NocoDB version : 0.83.6
Database used in NC_DB URL  : mysql
OS on which NocoDB is running : Ubuntu 21.10 (GNU/Linux 5.13.0-22-generic x86_64)

Hi,

I try to run Nocodb behing my traefik proxy, but I get « Gateway timeout » 99% of the time.

Here my docker-compose file :

```
version: '3.3'

services:
  root_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxx
      MYSQL_DATABASE: root_db
      MYSQL_USER: noco
      MYSQL_PASSWORD: xxxxxxxx
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - nocodb

  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    image: nocodb/nocodb:0.83.6
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9082:8082"
      - "8083:8083"
    restart: always
    environment:
      NC_DB: "mysql2://root_db:3306?u=noco&p=xxxxxxxxxx=root_db"
      NC_PUBLIC_URL: "https://nocodb.${DOMAINNAME}"
      NC_DISABLE_TELE: "true"
      NC_INVITE_ONLY_SIGNUP: "true"
    labels:
      #- "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.noco.rule=Host(`nocodb.${DOMAINNAME}`)"
      - "traefik.http.routers.noco.entrypoints=websecure"
      - "traefik.http.routers.noco.tls=true"
      - "traefik.http.routers.noco.tls.certresolver=letsencrypt"
      - "traefik.http.services.noco.loadbalancer.server.port=8080"
      - "traefik.http.routers.noco.middlewares=security-noco@file"
    networks:
      - nocodb
      - proxy
volumes:
  db_data: {}
networks:
  proxy:
    external: true
  nocodb:
    external: false
```

And my traefik_dynamic file :

```
[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
	"TLS_AES_128_GCM_SHA256",
	"TLS_CHACHA20_POLY1305_SHA256",
	"TLS_AES_256_GCM_SHA384",
	"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
	"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
	"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
      ]
      curvePreferences = ["CurveP521","CurveP384"]

[http]
  [http.services]

  [http.middlewares.compression.compress]
    excludedContentTypes = ["text/event-stream"]

  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"
    permanent = true

  [http.middlewares.security-noco.headers]
    accessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
    accessControlAllowOrigin = "origin-list-or-null"
    accessControlMaxAge = 100
    addVaryHeader = true
    browserXssFilter = true
    contentTypeNosniff = true
    forceSTSHeader = true
    frameDeny = true
    stsIncludeSubdomains = true
    stsPreload = true
    customFrameOptionsValue = "SAMEORIGIN"
    referrerPolicy = "same-origin"
    featurePolicy = "vibrate 'self'"
    stsSeconds = 315360000
```

Can’t figured out what’s wrong with it.

If any one have some input regarding this ?

Thanks

**Comment by danggrianto** [comment]
I got the same issue as well. My traefik configuration is the following

```
# http routing section
http:
  routers:
    # Define a connection between requests and services
    nocodb:
      rule: "Host(`nocodb.somehost.com`)"
      service: nocodb
      entrypoints: https
      tls:
        certresolver: http
    nocodb-redirect:
      rule: "Host(`nocodb.somehost.com`)"
      entrypoints: http
      service: nocodb
      middlewares: 
        - "nocodb-redirect"

  middlewares:
    nocodb-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    bookstack-redirect:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    nocodb:
      loadBalancer:
        servers:
          - url: http://0.0.0.0:8080
```
