### ISSUE TITLE
🐛 Bug: Cannot Edit JSON Field

### ISSUE THREAD

**Issue by colinbrust** [nocodb/nocodb#9387]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Spin up a Docker container using the `pg` compose file from [your GitHub](https://github.com/nocodb/nocodb/blob/develop/docker-compose/pg/docker-compose.yml):

```yaml
version: '2.1'
services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  root_db: 
    environment: 
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres
    restart: always
    volumes: 
      - "db_data:/var/lib/postgresql/data"
volumes: 
  db_data: {}
  nc_data: {}
```

After logging in to the main dashboard page, add a JSON typed column called 'test' to the `Getting Started` > `Features` table. Click on the cell in the new column and try to type `{'test': 1}`. I have tested this a number of times and one of the two following things happens: 

1. There is a blinking cursor in the box, but nothing appears when you type. 
2. You are able to enter the initial entry, but then the above issue happens when you try to make further edits. 

### Desired Behavior

You should be able to create and update entries in JSON columns like any other field type.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.255.2**
