### ISSUE TITLE
Could not parse JSON

### ISSUE THREAD

**Issue by winston0410** [nocodb/nocodb#945]
**Please enter the following details**

please provide the following details :
NocoDB used as docker : true
NocoDB version : latest docker image
Database used in NC_DB URL  : pg
Database on which spreadsheet is created : pg
OS on which NocoDB is running : NixOS

**Steps To Reproduce**
1. Use the following config, copied from the repository without change:

https://github.com/nocodb/nocodb/blob/master/docker-compose/pg/docker-compose.yml

```yaml
version: '2.1'

services:
  root_db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: root_db
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
volumes:
  db_data: {}

```
2. Go to `http://localhost:8080/dashboard`
3. Go to console and see the following error:
![1642009477](https://user-images.githubusercontent.com/59228178/149193714-66768dee-f582-450d-a991-ffaf96212499.jpg)

**Expected behavior**
No error and run nocodb properly

**Screenshots**

**Comment by wingkwong** [comment]
Could not reproduce the issue. Maybe remove your local ``nocodb/nocodb`` image and retry?

![image](https://user-images.githubusercontent.com/35857179/149362433-293a8cab-7bcc-43e7-b35d-7894d5912a0a.png)

Node: **v12.22.6**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.6**

**Comment by o1lab** [comment]
@winston0410 : if you had nocodb before. Try doing a hard refresh (cmd+shift+r or ctrl+shift+r)

**Comment by winston0410** [comment]
@o1lab No I don't have any running nocodb, and I am using a volume here, which shouldn't gives me any residue data after `docker-compose down`. I have tried again with tag `0.84.6`, but still it doesn't work and having the same error.

```yml
version: '2.1'

services:
  root_db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: root_db
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    image: nocodb/nocodb:0.84.6
    ports:
      - "8080:8080"
    restart: always
    environment:
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
```
