### ISSUE TITLE
🐛 Bug: can't signin in self-hosted

### ISSUE THREAD

**Issue by honcharov-viktor** [nocodb/nocodb#9568]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. create compose.yaml
```
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379

  nocodb:
    image: "nocodb/nocodb:latest"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      NC_DB: "pg://postgres:5432?u=root&p=root&d=nocodb"
      NC_REDIS_URL: "redis://redis:6379/4"
      NC_AUTOMATION_LOG_LEVEL: ALL
```
2. run `docker compose up -d redis postgres`
3. run `docker compose up nocodb`
4. open in browser http://yours_ip:8080/
5. signup with some credentials
6. go to database, in table `nc_users_v2` set for your user `email_verified: true, email_verification_token: null`
7. try to signin to nocodb (you can’t)

### Desired Behavior

I think condition in [signedIn Getters](https://github.com/nocodb/nocodb/blob/95734b9ea1f09f10d28994daae8d53b8e986852d/packages/nc-gui/composables/useGlobal/getters.ts#L4) is wrong cause nothing in app doesn’t set `state.jwtPayload` ([signIn action](https://github.com/nocodb/nocodb/blob/95734b9ea1f09f10d28994daae8d53b8e986852d/packages/nc-gui/composables/useGlobal/actions.ts#L34)).

### Project Details

Or manually fill in following info:

```
NocoDB used as docker : true
NocoDB version : 0.255.2 
Database used in NC_DB URL  : pg://postgres:5432?u=root&p=root&d=nocodb
OS on which NocoDB is running : Debian stable (bookworm)
```

### Attachments

https://github.com/user-attachments/assets/b2d8094b-dc47-47a8-b7b7-282c8eebfca1
